# engines
mysql: &mysql
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

# environments - change test and environment to suit your own setup
test:
  <<: *mysql
  database: work_progress_test
  username: root
  password: 
  host: localhost

development:
  <<: *mysql
  database: work_progress
  username: root
  password: 
  host: localhost